apiVersion: v1
kind: Service
metadata:
  name: starfleet-communications-service
spec:
  type: LoadBalancer

  selector:
    app: starfleet-communications-service

  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
