apiVersion: v1
kind: ServiceAccount
metadata:
  name: communications-service
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: communications-service@starfleet-gke-platform-lab.iam.gserviceaccount.com
